### ISSUE TITLE
Improve dark mode Toggle button with small css animation

### ISSUE THREAD

**Issue by gianpaj** [gianpaj/walnut.tv#234]
see https://escuela.dev/

- https://github.com/Escuela-dev/escuela.dev/blob/master/public/toggle-theme.js
- https://github.com/Escuela-dev/escuela.dev/blob/753f33eef68a3d868afae9e8c18b7cd0187954dc/src/components/Header.astro#L62

**Comment by y-kitazawa0** [comment]
Hi. I'm interesting this issue.can I work this issue?

Do you have any preferences for how you would like the animation to be?

**Comment by gianpaj** [comment]
Hey @y-kitazawa0 some simple like here:

https://app.tavily.com/sign-in

(After you sign in , in the dashboard page)

Ps: make sure to work on the `dev` branch :)💪

**Comment by y-kitazawa0** [comment]
@gianpaj 
Sorry I don't know that which repository can I work?

Escuela-dev repository?

**Comment by gianpaj** [comment]
@y-kitazawa0  no worries. this repo but on the `dev` branch

https://github.com/gianpaj/walnut.tv/tree/dev

if you have any questions or get stuck happy to help you on Telegram [gianpaj](https://telegram.me/gianpaj)

**Comment by y-kitazawa0** [comment]
@gianpaj 
Thank you so much 😊 
I try dev branch of this repo!
